# Generated by Django 5.0.6 on 2026-06-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_document_scan_result_document_scan_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='accession_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='document_category',
            field=models.CharField(choices=[('general', 'General Document'), ('imaging', 'Imaging File'), ('dicom', 'DICOM'), ('report', 'Report'), ('qc', 'QC Document'), ('baa', 'BAA')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='document',
            name='modality',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='document',
            name='patient_identifier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='study_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='study_instance_uid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
