# Generated by Django 5.0.6 on 2026-06-16 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0001_initial'),
        ('vault', '0004_document_accession_number_document_document_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='related_imaging_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='imaging.imagingstudy'),
        ),
    ]
