# Generated by Django 5.0.6 on 2026-06-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_document_related_imaging_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('document', 'Document'), ('spreadsheet', 'Spreadsheet'), ('presentation', 'Presentation'), ('image', 'Image'), ('dicom', 'DICOM'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
