# Generated by Django 5.0.6 on 2026-06-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_classification_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_classification_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_suggested_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
    ]
