# Generated by Django 5.0.6 on 2026-07-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('failed_login', 'Failed Login'), ('view_document', 'View Document'), ('download_document', 'Download Document'), ('upload_document', 'Upload Document'), ('delete_document', 'Delete Document'), ('restore_document', 'Restore Document'), ('update_document', 'Update Document'), ('permission_change', 'Permission Change'), ('create_share', 'Create Share'), ('create_folder', 'Create Folder'), ('mfa_enabled', 'MFA Enabled'), ('mfa_verified', 'MFA Verified'), ('export_package', 'Export Package'), ('access_imaging_viewer', 'Access Imaging Viewer')], max_length=100),
        ),
    ]
