# Generated by Django 5.0.6 on 2026-06-12 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('platform_admin', 'Platform Admin'), ('org_admin', 'Organization Admin'), ('facility_manager', 'Facility Manager'), ('staff', 'Staff'), ('external_reviewer', 'External Reviewer'), ('auditor', 'Auditor')], default='staff', max_length=50)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('facilities', models.ManyToManyField(blank=True, related_name='user_profiles', to='organizations.facility')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
