# Generated by Django 5.0.6 on 2026-07-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_orthanc',
            field=models.BooleanField(default=False, help_text='Grants access to the Orthanc imaging viewer link in the sidebar.'),
        ),
    ]
