# Generated by Django 5.0.6 on 2026-06-16 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRestoreTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_file', models.CharField(max_length=255)),
                ('result', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('restore_started_at', models.DateTimeField()),
                ('restore_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backup_restore_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
