# Generated by Django 5.0.6 on 2026-08-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0002_imagingstudy_labels_synced_at_orthancaccesstoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagingstudy',
            options={'ordering': ['-created_at']},
        ),
    ]
